language: ruby
cache: bundler
sudo: required

services:
  - docker

bundler_args: --jobs 7 --retry 3

rvm:
  - 2.1

branches:
  only:
    - master
    - /.*-alpha.*/

script:
  - bundle exec rake test
